version: "3.7"
services:
  database:
    image: postgres
    restart: always
    env_file: backends/.env
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
  api:
    build:
      context: backends
      dockerfile: Dockerfile
    env_file: backends/.env
    command: -config .env -migrations true
    depends_on:
      - database
    ports:
      - "8080:8080"
  web-client:
    build:
      context: web-client
      dockerfile: Dockerfile
    depends_on:
      - api
    ports:
      - "3000:3000"
volumes:
  data:
